"use client";

import { useI18n } from "../../../app/i18n/translations";
import { CHART_PALETTES, resolveChartPresentation } from "../presentation/chart-presentation";
import type { Aggregation, ChartColumn, ChartDefinition, ChartLineCurve, ChartPalette, ChartPresentation, ChartType, ThresholdRule } from "../types/chart-types";

const types: Array<{ id: ChartType; icon: string }> = [
  { id: "line", icon: "⌁" }, { id: "bar", icon: "▥" }, { id: "area", icon: "◩" },
  { id: "scatter", icon: "⁙" }, { id: "histogram", icon: "▤" }, { id: "boxplot", icon: "⊟" },
  { id: "heatmap", icon: "▦" }, { id: "pareto", icon: "▥" }, { id: "waterfall", icon: "▟" },
  { id: "control", icon: "⌁" }, { id: "forecast", icon: "↗" },
];
const aggregationIds: Aggregation[] = ["sum", "average", "min", "max", "count"];

type Props = {
  draft: ChartDefinition;
  columns: ChartColumn[];
  errors: string[];
  editing: boolean;
  onChange: (definition: ChartDefinition) => void;
  onSubmit: () => void;
  onCancelEdit: () => void;
};

export function ChartBuilder({ draft, columns, errors, editing, onChange, onSubmit, onCancelEdit }: Props) {
  const { language } = useI18n();
  const tr = (pl: string, en: string) => language === "en" ? en : pl;
  const typeLabels: Record<ChartType, string> = { line: tr("Linia", "Line"), bar: tr("Słupki", "Bars"), area: tr("Obszar", "Area"), scatter: tr("Punkty", "Scatter"), histogram: "Histogram", boxplot: tr("Pudełkowy", "Box plot"), heatmap: tr("Mapa ciepła", "Heatmap"), pareto: "Pareto", waterfall: "Waterfall", control: tr("Kontrolny", "Control"), forecast: tr("Prognoza", "Forecast") };
  const aggregationLabels: Record<Aggregation, string> = { sum: tr("Suma", "Sum"), average: tr("Średnia", "Average"), min: "Minimum", max: "Maximum", count: tr("Liczba rekordów", "Record count") };
  const numeric = columns.filter((column) => column.type === "number");
  const dates = columns.filter((column) => column.type === "date");
  const filter = draft.filters[0];
  const presentation = resolveChartPresentation(draft.presentation);
  const update = (patch: Partial<ChartDefinition>) => onChange({ ...draft, ...patch });
  const updatePresentation = (patch: Partial<ChartPresentation>) => update({ presentation: { ...presentation, ...patch } });
  const updateCustomColor = (index: number, color: string) => {
    const customColors = [...(presentation.customColors?.length ? presentation.customColors : CHART_PALETTES.ocean)];
    customColors[index] = color;
    updatePresentation({ palette: "custom", customColors });
  };
  const toggleY = (field: string) => {
    const yFields = draft.yFields.includes(field) ? draft.yFields.filter((item) => item !== field) : [...draft.yFields, field];
    const comparison = draft.comparison && yFields.includes(draft.comparison.referenceField) ? draft.comparison : undefined;
    const thresholds = (draft.thresholds ?? []).filter((rule) => yFields.includes(rule.field));
    update({ yFields, comparison, thresholds, seriesField: yFields.length > 1 ? undefined : draft.seriesField });
  };
  const updateThreshold = (id: string, patch: Partial<ThresholdRule>) => update({ thresholds: (draft.thresholds ?? []).map((rule) => rule.id === id ? { ...rule, ...patch } : rule) });
  const addThreshold = () => {
    const field = draft.yFields.find((candidate) => !(draft.thresholds ?? []).some((rule) => rule.field === candidate)) ?? draft.yFields[0];
    if (!field) return;
    update({ thresholds: [...(draft.thresholds ?? []), { id: `limit-${Date.now()}`, field, mode: "percentile", percentile: 90, direction: "above", label: "P90", severity: "warning", evaluation: "raw", enabled: true }] });
  };

  return (
    <aside className="chart-builder">
      <div className="builder-title"><span>{editing ? tr("EDYCJA WYKRESU", "EDIT CHART") : tr("NOWY WYKRES", "NEW CHART")}</span><strong>{tr("Mapowanie danych", "Data mapping")}</strong></div>
      <label className="builder-field">{tr("Nazwa wykresu", "Chart name")}<input value={draft.title} onChange={(event) => update({ title: event.target.value })} /></label>
      <div className="builder-field"><span>{tr("Typ wizualizacji", "Visualization type")}</span><div className="chart-type-grid">{types.map((type) => <button key={type.id} className={draft.type === type.id ? "active" : ""} onClick={() => update({ type: type.id, yFields: type.id === "histogram" ? [] : draft.yFields, seriesField: type.id === "histogram" ? undefined : draft.seriesField })}><i>{type.icon}</i>{typeLabels[type.id]}</button>)}</div></div>
      <details className="builder-section appearance-builder" open>
        <summary><span>{tr("Wygląd wykresu", "Chart appearance")}</span><small>{tr("kolory, linie i etykiety", "colors, lines and labels")}</small></summary>
        <div className="builder-section-content">
          <div className="builder-field"><span>{tr("Paleta kolorów", "Color palette")}</span><div className="palette-grid">{(["theme", "ocean", "violet", "sunset", "mono", "custom"] as ChartPalette[]).map((palette) => {
            const swatches = palette === "theme" ? CHART_PALETTES.ocean : palette === "custom" ? (presentation.customColors ?? CHART_PALETTES.ocean) : CHART_PALETTES[palette];
            const labels: Record<ChartPalette, string> = { theme: tr("Motyw", "Theme"), ocean: "Ocean", violet: tr("Fiolet", "Violet"), sunset: tr("Zachód", "Sunset"), mono: "Mono", custom: tr("Własne", "Custom") };
            return <button key={palette} className={presentation.palette === palette ? "active" : ""} onClick={() => updatePresentation({ palette })}><i>{swatches.slice(0, 3).map((color) => <b key={color} style={{ background: color }} />)}</i>{labels[palette]}</button>;
          })}</div></div>
          {presentation.palette === "custom" && <div className="builder-field custom-color-row"><span>{tr("Kolory serii", "Series colors")}</span><div>{Array.from({ length: Math.max(3, Math.min(5, draft.yFields.length || 3)) }, (_, index) => <label key={index}><input type="color" value={(presentation.customColors ?? CHART_PALETTES.ocean)[index] ?? CHART_PALETTES.ocean[index]} onChange={(event) => updateCustomColor(index, event.target.value)} /><small>{draft.yFields[index] ?? `${tr("Seria", "Series")} ${index + 1}`}</small></label>)}</div></div>}
          {(["line", "area"].includes(draft.type)) && <div className="appearance-two-column">
            <label className="builder-field">{tr("Przebieg linii", "Line shape")}<select value={presentation.lineCurve} onChange={(event) => updatePresentation({ lineCurve: event.target.value as ChartLineCurve })}><option value="smooth">{tr("Wygładzony", "Smooth")}</option><option value="straight">{tr("Prosty", "Straight")}</option><option value="step">{tr("Schodkowy", "Stepped")}</option></select></label>
            <label className="builder-field">{tr("Grubość linii", "Line width")}<select value={presentation.lineWidth} onChange={(event) => updatePresentation({ lineWidth: Number(event.target.value) })}><option value="1">{tr("Cienka", "Thin")}</option><option value="2">{tr("Standardowa", "Standard")}</option><option value="3">{tr("Wyraźna", "Strong")}</option><option value="5">{tr("Gruba", "Thick")}</option></select></label>
          </div>}
          {draft.type === "area" && <label className="builder-field range-builder">{tr("Wypełnienie obszaru", "Area fill")} <strong>{presentation.areaOpacity}%</strong><input type="range" min="5" max="65" step="5" value={presentation.areaOpacity} onChange={(event) => updatePresentation({ areaOpacity: Number(event.target.value) })} /></label>}
          {draft.type === "bar" && <div className="appearance-two-column"><label className="builder-field">{tr("Kierunek słupków", "Bar direction")}<select value={presentation.barOrientation} onChange={(event) => updatePresentation({ barOrientation: event.target.value as ChartPresentation["barOrientation"] })}><option value="vertical">{tr("Pionowe", "Vertical")}</option><option value="horizontal">{tr("Poziome", "Horizontal")}</option></select></label><label className="builder-field">{tr("Układ serii", "Series layout")}<select value={presentation.stacked ? "stacked" : "grouped"} onChange={(event) => updatePresentation({ stacked: event.target.value === "stacked" })}><option value="grouped">{tr("Obok siebie", "Grouped")}</option><option value="stacked">{tr("Skumulowane", "Stacked")}</option></select></label></div>}
          <label className="builder-field">{tr("Legenda", "Legend")}<select value={presentation.legendPosition} onChange={(event) => updatePresentation({ legendPosition: event.target.value as ChartPresentation["legendPosition"] })}><option value="top">{tr("Nad wykresem", "Above chart")}</option><option value="bottom">{tr("Pod wykresem", "Below chart")}</option><option value="hidden">{tr("Ukryta", "Hidden")}</option></select></label>
          <div className="appearance-switches">
            {!(["bar", "histogram"].includes(draft.type)) && <button className={presentation.showSymbols ? "active" : ""} onClick={() => updatePresentation({ showSymbols: !presentation.showSymbols })}><i>{presentation.showSymbols ? "✓" : ""}</i>{tr("Punkty danych", "Data points")}</button>}
            <button className={presentation.showDataLabels ? "active" : ""} onClick={() => updatePresentation({ showDataLabels: !presentation.showDataLabels })}><i>{presentation.showDataLabels ? "✓" : ""}</i>{tr("Etykiety wartości", "Value labels")}</button>
            <button className={presentation.showGrid ? "active" : ""} onClick={() => updatePresentation({ showGrid: !presentation.showGrid })}><i>{presentation.showGrid ? "✓" : ""}</i>{tr("Linie siatki", "Grid lines")}</button>
            <button className={presentation.showZoom ? "active" : ""} onClick={() => updatePresentation({ showZoom: !presentation.showZoom })}><i>{presentation.showZoom ? "✓" : ""}</i>{tr("Nawigacja zakresu", "Range navigation")}</button>
            <button className={presentation.showBrush ? "active" : ""} onClick={() => updatePresentation({ showBrush: !presentation.showBrush })}><i>{presentation.showBrush ? "✓" : ""}</i>{tr("Zaznaczanie danych", "Data selection")}</button>
          </div>
        </div>
      </details>
      <label className="builder-field">{tr("Oś X", "X axis")}<select value={draft.xField} onChange={(event) => update({ xField: event.target.value })}><option value="">{tr("Wybierz kolumnę…", "Select a column…")}</option>{columns.map((column) => <option key={column.name} value={column.name}>{column.name} · {column.type}</option>)}</select></label>
      {dates.length > 0 && <details className="builder-section time-window-builder" open><summary><span>{tr("Dzień i godzina", "Date and time")}</span><small>{tr("wybierz dokładny zakres", "select an exact range")}</small></summary><div className="builder-section-content"><label className="builder-field">{tr("Kolumna czasu", "Time column")}<select value={draft.timeRange?.field ?? ""} onChange={(event) => update({ timeRange: event.target.value ? { field: event.target.value, from: draft.timeRange?.from, to: draft.timeRange?.to } : undefined })}><option value="">{tr("Cały dostępny okres", "Entire available period")}</option>{dates.map((column) => <option key={column.name} value={column.name}>{column.name}</option>)}</select></label>{draft.timeRange && <div className="time-range-inputs"><label>{tr("Od dnia i godziny", "From date and time")}<input type="datetime-local" step="60" value={draft.timeRange.from ?? ""} onChange={(event) => update({ timeRange: { ...draft.timeRange!, from: event.target.value || undefined } })} /></label><label>{tr("Do dnia i godziny", "To date and time")}<input type="datetime-local" step="60" value={draft.timeRange.to ?? ""} onChange={(event) => update({ timeRange: { ...draft.timeRange!, to: event.target.value || undefined } })} /></label></div>}<small className="builder-help">{tr("Zakres jest zapisywany razem z wykresem i działa również po zastosowaniu szablonu.", "The range is saved with the chart and remains active when a template is applied.")}</small></div></details>}
      {draft.type !== "histogram" && <div className="builder-field"><span>{tr("Wartości Y", "Y values")} <small>{tr("możesz wybrać kilka", "you can select several")}</small></span><div className="field-checks">{numeric.map((column) => <button key={column.name} className={draft.yFields.includes(column.name) ? "selected" : ""} onClick={() => toggleY(column.name)}><i>{draft.yFields.includes(column.name) ? "✓" : "+"}</i>{column.name}</button>)}</div></div>}
      {draft.type !== "scatter" && draft.type !== "histogram" && <><label className="builder-field">{tr("Obliczenie", "Calculation")}<select value={draft.formula ? "formula" : draft.aggregation} onChange={(event) => event.target.value === "formula" ? update({ formula: { expression: draft.formula?.expression || (numeric[0] ? `[${numeric[0].name}]` : ""), label: draft.formula?.label || tr("Własne obliczenie", "Custom calculation") }, comparison: undefined, thresholds: [] }) : update({ aggregation: event.target.value as Aggregation, formula: undefined })}>{aggregationIds.map((id) => <option key={id} value={id}>{aggregationLabels[id]}</option>)}<option value="formula">{tr("Własna formuła…", "Custom formula…")}</option></select></label>{draft.formula && <div className="builder-field chart-formula-builder"><span>{tr("Własne obliczenie", "Custom calculation")} <small>{tr("liczone dla każdego rekordu", "calculated for every record")}</small></span><label>{tr("Nazwa wyniku", "Result name")}<input value={draft.formula.label} onChange={(event) => update({ formula: { ...draft.formula!, label: event.target.value } })} placeholder={tr("np. Odchylenie od zadanej", "e.g. Deviation from target")} /></label><label>{tr("Formuła", "Formula")}<textarea className="formula-editor" value={draft.formula.expression} onChange={(event) => update({ formula: { ...draft.formula!, expression: event.target.value } })} placeholder="e.g. [Dancer_Process_Value] - [Dancer_Setpoint]" /></label><div className="formula-field-chips"><span>{tr("Wstaw kolumnę:", "Insert column:")}</span>{numeric.slice(0, 16).map((column) => <button key={column.name} onClick={() => update({ formula: { ...draft.formula!, expression: `${draft.formula!.expression}${draft.formula!.expression ? " " : ""}[${column.name}]` } })}>{column.name}</button>)}</div><label>{tr("Połącz rekordy o tym samym X", "Combine records with the same X")}<select value={draft.aggregation} onChange={(event) => update({ aggregation: event.target.value as Aggregation })}>{aggregationIds.filter((id) => id !== "count").map((id) => <option key={id} value={id}>{aggregationLabels[id]}</option>)}</select></label><small className="builder-help">{tr("Podgląd wykresu po prawej aktualizuje się od razu. Dostępne: +, −, ×, ÷, ^ oraz abs(), min(), max(), round(), sqrt(), pow(). Nazwy kolumn wpisuj w [nawiasach].", "The chart preview on the right updates immediately. Available: +, −, ×, ÷, ^ and abs(), min(), max(), round(), sqrt(), pow(). Put column names in [brackets].")}</small></div>}</>}
      {draft.type === "forecast" && <label className="builder-field">{tr("Horyzont prognozy", "Forecast horizon")}<select value={draft.diagnostic?.forecastHorizon ?? 6} onChange={(event) => update({ diagnostic: { ...draft.diagnostic, forecastHorizon: Number(event.target.value) } })}>{[3, 6, 12, 24].map((period) => <option key={period} value={period}>{period} {tr(period === 3 ? "okresy" : "okresów", "periods")}</option>)}</select></label>}
      {draft.type === "control" && <label className="builder-field">{tr("Granice kontrolne", "Control limits")}<select value={draft.diagnostic?.controlSigma ?? 3} onChange={(event) => update({ diagnostic: { ...draft.diagnostic, controlSigma: Number(event.target.value) } })}><option value="2">±2σ</option><option value="3">±3σ</option></select></label>}
      {draft.type !== "histogram" && draft.yFields.length === 1 && <label className="builder-field">{tr("Podziel na serie", "Split into series")}<select value={draft.seriesField ?? ""} onChange={(event) => update({ seriesField: event.target.value || undefined })}><option value="">{tr("Bez podziału", "No split")}</option>{columns.filter((column) => column.name !== draft.xField && !draft.yFields.includes(column.name)).map((column) => <option key={column.name} value={column.name}>{column.name}</option>)}</select></label>}
      {draft.yFields.length > 1 && <label className="builder-field">{tr("Pokaż różnicę", "Show difference")}<select value={draft.comparison?.referenceField ?? ""} onChange={(event) => update({ comparison: event.target.value ? { referenceField: event.target.value, mode: draft.comparison?.mode ?? "percent" } : undefined })}><option value="">{tr("Wyłączone", "Off")}</option>{draft.yFields.map((field) => <option key={field} value={field}>{tr("Względem", "Compared with")}: {field}</option>)}</select></label>}
      {draft.comparison && <div className="comparison-mode"><button className={draft.comparison.mode === "absolute" ? "active" : ""} onClick={() => update({ comparison: { ...draft.comparison!, mode: "absolute" } })}>{tr("Wartość", "Value")}</button><button className={draft.comparison.mode === "percent" ? "active" : ""} onClick={() => update({ comparison: { ...draft.comparison!, mode: "percent" } })}>{tr("Procent", "Percent")}</button></div>}
      {draft.type !== "histogram" && !draft.formula && <div className="builder-field threshold-builder"><span>{tr("Linie odniesienia i alerty", "Reference lines and alerts")} <button onClick={addThreshold} disabled={!draft.yFields.length}>＋ {tr("Dodaj", "Add")}</button></span>{(draft.thresholds ?? []).length === 0 && <small className="threshold-empty">{tr("Dodaj wartość ręczną albo percentyl, np. P90.", "Add a manual value or percentile, e.g. P90.")}</small>}{(draft.thresholds ?? []).map((rule) => <div className="threshold-rule" key={rule.id}>
        <div><select aria-label={tr("Seria limitu", "Limit series")} value={rule.field} onChange={(event) => updateThreshold(rule.id, { field: event.target.value })}>{draft.yFields.map((field) => <option value={field} key={field}>{field}</option>)}</select><button aria-label={tr("Usuń limit", "Remove limit")} onClick={() => update({ thresholds: draft.thresholds.filter((item) => item.id !== rule.id) })}>×</button></div>
        <div className="threshold-mode-row"><label>{tr("Rodzaj", "Type")}<select value={rule.mode ?? "manual"} onChange={(event) => updateThreshold(rule.id, { mode: event.target.value as ThresholdRule["mode"], label: event.target.value === "percentile" ? `P${rule.percentile ?? 90}` : rule.label })}><option value="percentile">{tr("Percentyl", "Percentile")}</option><option value="manual">{tr("Ręczny zakres", "Manual range")}</option></select></label><label>{tr("Poziom alertu", "Alert level")}<select value={rule.severity ?? "warning"} onChange={(event) => updateThreshold(rule.id, { severity: event.target.value as ThresholdRule["severity"] })}><option value="info">{tr("Informacja", "Information")}</option><option value="warning">{tr("Ostrzeżenie", "Warning")}</option><option value="critical">{tr("Krytyczne", "Critical")}</option></select></label></div>
        {(rule.mode ?? "manual") === "percentile" ? <><div><label>{tr("Poziom obserwacji", "Observation level")}<select value={rule.percentile ?? 90} onChange={(event) => updateThreshold(rule.id, { percentile: Number(event.target.value), label: `P${event.target.value}` })}><option value="75">75% (P25 / P75)</option><option value="90">90% (P10 / P90)</option><option value="95">95% (P5 / P95)</option><option value="99">99% (P1 / P99)</option></select></label><label>{tr("Alarmuj, gdy", "Alert when")}<select value={rule.direction ?? "above"} onChange={(event) => updateThreshold(rule.id, { direction: event.target.value as ThresholdRule["direction"] })}><option value="above">{tr("powyżej górnej granicy", "above upper boundary")}</option><option value="below">{tr("poniżej dolnej granicy", "below lower boundary")}</option></select></label></div><small className="threshold-tail-hint">{(rule.direction ?? "above") === "below" ? tr(`Dolna granica: P${100 - (rule.percentile ?? 90)} dla poziomu ${rule.percentile ?? 90}%.`, `Lower boundary: P${100 - (rule.percentile ?? 90)} at the ${rule.percentile ?? 90}% level.`) : tr(`Górna granica: P${rule.percentile ?? 90} dla poziomu ${rule.percentile ?? 90}%.`, `Upper boundary: P${rule.percentile ?? 90} at the ${rule.percentile ?? 90}% level.`)}</small></> : <><div><label>{tr("Dolna granica", "Lower boundary")}<input type="number" value={rule.lower ?? ""} placeholder={tr("np. 40", "e.g. 40")} onChange={(event) => updateThreshold(rule.id, { lower: event.target.value === "" ? undefined : Number(event.target.value) })} /></label><label>{tr("Górna granica", "Upper boundary")}<input type="number" value={rule.upper ?? ""} placeholder={tr("np. 60", "e.g. 60")} onChange={(event) => updateThreshold(rule.id, { upper: event.target.value === "" ? undefined : Number(event.target.value) })} /></label></div><small className="threshold-tail-hint">{tr("Ustaw obie granice, aby pokazać dozwolony zakres. Dotknięcie lub wyjście poza granicę trafi do raportu z dokładnym czasem.", "Set both boundaries to show the allowed range. Touching or crossing a boundary is recorded in the report with the exact time.")}</small></>}
        <input aria-label={tr("Nazwa linii odniesienia", "Reference line name")} value={rule.label ?? ""} placeholder={tr("Nazwa, np. zakres pracy 40–60", "Name, e.g. operating range 40–60")} onChange={(event) => updateThreshold(rule.id, { label: event.target.value })} />
        <input aria-label={tr("Opis konsekwencji", "Consequence description")} value={rule.description ?? ""} placeholder={tr("Opcjonalnie: co oznacza przekroczenie?", "Optional: what does a violation mean?")} onChange={(event) => updateThreshold(rule.id, { description: event.target.value })} />
        <select aria-label={tr("Sposób sprawdzania limitu", "Limit evaluation method")} value={rule.evaluation} onChange={(event) => updateThreshold(rule.id, { evaluation: event.target.value as ThresholdRule["evaluation"] })}><option value="plotted">{tr("Wartość widoczna na wykresie", "Value shown on chart")}</option><option value="raw">{tr("Każdy rekord źródłowy", "Every source record")}</option></select>
      </div>)}</div>}
      <div className="builder-field filter-builder"><span>{tr("Filtr opcjonalny", "Optional filter")}</span><select value={filter?.field ?? ""} onChange={(event) => update({ filters: event.target.value ? [{ field: event.target.value, operator: "equals", value: "" }] : [] })}><option value="">{tr("Bez filtra", "No filter")}</option>{columns.map((column) => <option key={column.name} value={column.name}>{column.name}</option>)}</select>{filter && <><select value={filter.operator} onChange={(event) => update({ filters: [{ ...filter, operator: event.target.value as typeof filter.operator }] })}><option value="equals">{tr("równa się", "equals")}</option><option value="contains">{tr("zawiera", "contains")}</option><option value="greater">{tr("większe niż", "greater than")}</option><option value="less">{tr("mniejsze niż", "less than")}</option></select><input value={filter.value} placeholder={tr("Wartość filtra", "Filter value")} onChange={(event) => update({ filters: [{ ...filter, value: event.target.value }] })} /></>}</div>
      <label className="builder-field">{tr("Rozmiar kafelka", "Tile size")}<select value={draft.size} onChange={(event) => update({ size: event.target.value as ChartDefinition["size"] })}><option value="small">{tr("Mały", "Small")}</option><option value="medium">{tr("Średni", "Medium")}</option><option value="large">{tr("Duży", "Large")}</option></select></label>
      {errors.length > 0 && <div className="chart-errors">{errors.map((error) => <span key={error}>! {error}</span>)}</div>}
      <div className="builder-actions"><button className="primary-button" disabled={errors.length > 0} onClick={onSubmit}>{editing ? tr("Zapisz zmiany", "Save changes") : tr("Dodaj do pulpitu", "Add to dashboard")}</button>{editing && <button className="secondary-button" onClick={onCancelEdit}>{tr("Anuluj", "Cancel")}</button>}</div>
    </aside>
  );
}
